FashionShop/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FashionShop.Models;

namespace FashionShop.Areas.Admin.Controllers
{
    public class PostController : AdminAppController
    {
        //private ModelDBContext db = new ModelDBContext();

        //
        // GET: /Admin/Post/

        public ActionResult Index()
        {
            var post = db.Post.Include(p => p.User);
            return View(post.ToList());
        }

        //
        // GET: /Admin/Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Admin/Post/Create

        public ActionResult Create()
        {
            //ViewBag.UserID = new SelectList(db.User, "UserID", "Username");
            return View();
        }

        //
        // POST: /Admin/Post/Create

        [HttpPost]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.UserID = Int32.Parse(Session["UserID"].ToString());
                post.AddCreatedTime();
                post.URL = UrlUtil.GenerateUrl(post.Title);

                db.Post.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.UserID = new SelectList(db.User, "UserID", "Username", post.UserID);
            return View(post);
        }

        //
        // GET: /Admin/Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            //ViewBag.UserID = new SelectList(db.User, "UserID", "Username", post.UserID);
            return View(post);
        }

        //
        // POST: /Admin/Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                post.UpdateModifiedTime();
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.User, "UserID", "Username", post.UserID);
            return View(post);
        }

        //
        // GET: /Admin/Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Admin/Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Post.Find(id);
            db.Post.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FashionShop/Areas/Home/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Areas.Home.Controllers
{
    public class BrandController : HomeAppController
    {
        //
        // GET: /Home/Brand/

        public ActionResult Index()
        {
            return View();
        }

    }
}

FashionShop/Areas/Admin/Views/Shared/Elements/AdLeftMenu.cshtml
<div id="left-menu">
    <ul class="nav nav-pills nav-stacked">
      <li class="nav-header disabled"><a href="#">Dash board</a></li>
        <li id="lm-customer">@Html.ActionLink("Khách hàng","Index", "Customer")</li>
      <li id="lm-location">@Html.ActionLink("Nơi sản xuất","Index", "Location")</li>
       <li id="lm-image">@Html.ActionLink("Ảnh","Index", "Image")</li>
       <li id="lm-user">@Html.ActionLink("Người dùng","Index", "User")</li>
        <li id="lm-group">@Html.ActionLink("Nhóm","Index", "Group")</li>
    </ul>
</div>

FashionShop/Areas/Admin/Views/Shared/Elements/AdPagination.cshtml
@{
    int min = (ViewBag.CurrentPage > 3) ? (ViewBag.CurrentPage - 3) : 1;
    int max = ((ViewBag.CurrentPage + 3) < ViewBag.MaxPage) ? ViewBag.CurrentPage + 3 : ViewBag.MaxPage;  
}
@if(ViewBag.MaxPage > 1){
    <ul class="pagination">
         @if(ViewBag.CurrentPage != 1){
                <li><a href="?page=1">&laquo;</a></li>
         }
    @for(int i = min; i <= max; i++){
        if(i != ViewBag.CurrentPage){   
            <li><a href="?page=@i">@i</a></li>
        }else{
             <li class="active"><a href="javascript:void(0)">@i</a></li>
        }
    }
        @if(ViewBag.CurrentPage != ViewBag.MaxPage){
            <li><a href="?page=@ViewBag.MaxPage">&raquo;</a></li>
        }
    </ul>
}

FashionShop/Areas/Admin/Views/Shared/Elements/AdProductTabs.cshtml
<ul class="nav nav-tabs">
  <li @ViewBag.Misc.IsActive("/Admin/AdProduct", ViewBag.CurrentUrl)>@Html.ActionLink("Tất cả sản phẩm","Index")</li>
  <li @ViewBag.Misc.IsActive("/Admin/AdProduct/Create", ViewBag.CurrentUrl)>@Html.ActionLink("Thêm sản phẩm", "Create")</li>
</ul>

FashionShop/Areas/Admin/Views/Shared/Elements/AdTopMenu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Fashion Shop</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li id="tm-home">@Html.ActionLink("Home", "index",  new { area = "Home", controller = "Home", action = "Index" })</li>
              <li id="tm-post">@Html.ActionLink("Bài viết","Index", "Post")</li>
            <li id="tm-product">@Html.ActionLink("Sản phẩm","Index", "Product")</li>
            <li id="tm-brand">@Html.ActionLink("Thương hiệu","Index", "Brand")</li>
            <li id="tm-catalogue">@Html.ActionLink("Phân loại","Index", "ProductCatalogue")</li>
            @if(Session["Username"] != null){
              <li class="dropdown">               
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Xin chào, @Session["Username"] <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Đăng xuất","Logout", "User")</li>
                      </ul>
                  
                @*<li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>*@
              
            </li>
            }
          </ul>
        </div><!--/.nav-collapse -->
      </div> <!--.container-->
    </div>